[package]
name = "recover"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2.5.0"
anyhow = "1.0.95"
clap = { version = "4.5.29", features = ["derive"] }